uploads = []
generated = []

[[outputs]]
id = "RG25Vm6yGyL2OLnL05U4a"
uri = "file://truth-md.tar.gz"
type = "unspecified"
title = "TRUTH-MD — Full Project (Upload to Pterodactyl)"

[[outputs]]
id = "kyxF0heMicVEUj2G6QKwh"
uri = "file://truth-md-pterodactyl.tar.gz"
type = "unspecified"
title = "TRUTH-MD — Ready for Pterodactyl (Upload & Start)"

[[outputs]]
id = "JQgZTJTDQTQ7IVMI1IMM7"
uri = "file://truth-md-deploy.tar.gz"
type = "unspecified"
title = "TRUTH-MD — Full Deployment Package (5.2MB)"

[[outputs]]
id = "vzlFxay9wcTUFuCWNQXxR"
uri = "file://truth-md-final.tar.gz"
type = "unspecified"
title = "TRUTH-MD — Final Build (No Install Required)"
